# Generated by Django 3.2.12 on 2022-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220322_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='bring_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
