# Generated by Django 3.2.12 on 2022-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220325_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Productcategory',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
