# Generated by Django 3.2.12 on 2022-03-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_shoppinglistitem_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='bring_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
