# Generated by Django 3.2.12 on 2022-03-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_shoppinglist_bring_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='day_of_the_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Truesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
