# Generated by Django 3.2.12 on 2022-03-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_shoppinglist_day_of_the_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
