# Generated by Django 3.2.12 on 2022-03-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='food_item_id',
            new_name='food_item',
        ),
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
