# Generated by Django 3.2.12 on 2022-03-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20220320_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
