# Generated by Django 3.2.12 on 2022-03-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_shoppinglistitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='meal.meal'),
        ),
    ]
