# Generated by Django 3.2.12 on 2022-03-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_alter_shoppinglistitem_meal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='food_item',
            new_name='ingredient',
        ),
    ]
