# Generated by Django 3.2.12 on 2022-03-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20220321_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
