#!/usr/bin/env sh

heroku config --shell --app $HEROKU_APP_NAME |
sed s/ENVIRONMENT=staging/ENVIRONMENT=development/ |
sed s/DJANGO_ENVIRONMENT=staging/DJANGO_ENVIRONMENT=develop/ |
sed s/DEBUG=False// |
sed -E s/^\(DATABASE_URL\|HEROKU_POSTGRESQL_\[A-Z\]\+_URL\|SEGMENT_WRITE_KEY\|R7_INSIGHTS_TOKEN\|NEW_RELIC\).*$// |
sed s/\\\\n/'\\\\\n'/g > .env
